### ISSUE TITLE
Any way to optimize pacnews so it uses users neovim configs?

### ISSUE THREAD

**Issue by thepenguinthatwants** [pbrisbin/dotfiles#2]
Hi,
right now it uses up root user but wondering if there could be a way to set it to use normal users nvim configs for the diff.

**Comment by pbrisbin** [comment]
Good question.

FYI `pacnews` is no longer even in this repository, I stopped using it as there are a lot of other tools in the space, and I've been happy with `pacdiff` myself. Maybe one of them supports what you need?

https://wiki.archlinux.org/title/Pacman/Pacnew_and_Pacsave#Managing_.pac*_files

However, for my old `pacnews` script, you could try one of the following:

- Use `vim -u /path/to/user/config`, might be easy if the script respects `EDITOR` or `VISUAL`, to say `EDITOR='vim -u ...' pacnews`
- Try and symlink `/root/.config/nvim/init.vim` to `/path/to/user/config`. This would make any editing by root use that configuration, but it could break if your config requires other support files, such as plugins

Good luck!
